Fix removal of the last record in a database

diff --git a/lib/gim/dbi b/lib/gim/dbi
--- a/lib/gim/dbi
+++ b/lib/gim/dbi
@@ -53,7 +53,14 @@ dbi_insert() {
 # PARAMETERS:
 #   $1 - short URL
 dbi_delete() {
-    dbi_deleted="$(grep -F -v "$1" -- "$GIM_STATUS_PATH")" &&
+    dbi_deleted="$(grep -F -v "$1" -- "$GIM_STATUS_PATH")"
+
+    dbi_grep_status="$?" # store exit status of called grep
+    # do not return fail when grep failed because there were no lines selected
+    if [ "$dbi_grep_status" -ne 0 ] && [ "$dbi_grep_status" -ne 1 ]; then
+        return "$dbi_grep_status"
+    fi
+
     echo "$dbi_deleted" > "$GIM_STATUS_PATH"
 }
 
