Improve a valid Git URL format detection

diff --git a/build/gim b/build/gim
--- a/build/gim
+++ b/build/gim
@@ -12,7 +12,7 @@
 #-------------------------------------------------------------------------------
 
 # list of required software
-SW_REQUIRED='command echo [ git make cd mkdir sed'
+SW_REQUIRED='command echo [ git make cd mkdir sed grep'
 
 # check if some software is missing
 for i in $SW_REQUIRED; do
@@ -38,9 +38,9 @@ VERSION=1.0.0
 HELP_MESSAGE="Usage: $0 [OPTION]... ACTION GIT_URL
 
 ACTION:
-  install    install the program originating from a given Git URL
-  uninstall  uninstall the program originating from a given Git URL
-  update     update the program originating from a given Git URL
+  install    install a program originating from the given Git URL
+  uninstall  uninstall a program originating from the given Git URL
+  update     update a program originating from the given Git URL
 
 OPTION:
   -help     show this help and exit
@@ -54,7 +54,7 @@ Copy"'right 2018 Dominik Salvet
 SPDX License Identifier: MIT
 https://gitlab.com/dominiksalvet/gim'
 
-# cache directory used to store download Git repositories
+# cache directory to store downloaded Git repositories
 CACHE_DIR=~/.cache/gim
 
 #-------------------------------------------------------------------------------
@@ -63,8 +63,8 @@ CACHE_DIR=~/.cache/gim
 
 # processing each parameter separately
 for i in "$@"; do
-    if [ ! -z "$action" ]; then
-        # the action has been selected in the previous variable, get Git URL
+    if [ ! -z "$action" ]; then # if the action has been selected in the previous variable
+        # get Git URL and discard all following parameters
         git_url="$i"
         break
     else
@@ -100,31 +100,27 @@ Try '$0 -help' for more information." >&2
 done
 
 # check arguments if valid
-if [ -z "$action" ]; then
+if [ -z "$action" ]; then # check if ACTION argument provided
     echo "$0: No argument with action provided.
 Try '$0 -help' for more information." >&2
     exit 1
-else
-    if [ -z "$git_url" ]; then
-        echo "$0: No argument with URL provided.
+elif [ -z "$git_url" ]; then # check if GIT_URL argument provided
+    echo "$0: No argument with Git URL provided.
 Try '$0 -help' for more information." >&2
-        exit 1
-    else
-        case "$git_url" in
-            *.git)
-                # parse project and author name from a given Git URL
-                git_url_project="$(echo "$git_url" | sed -E -e 's/.git$//; s|.*/||')"
-                git_url_author="$(echo "$git_url" | sed -E -e 's|/[^/]*$||; s|.*/||')"
-                ;;
-        esac
+    exit 1
+else # both arguments provided
 
-        if [ -z "$git_url_project" ] || [ -z "$git_url_author" ]; then
-            echo "$0: Provided Git URL is invalid.
+    # check the format of given Git URL
+    if ! echo "$git_url" | grep -q -E -e 'https://[^\.]+\.[^/]+/[^/]+/[^\.]+\.git'; then
+        echo "$0: Supplied Git URL is invalid.
 POSSIBLE SOLUTIONS:
   * use the 'https://<provider>.<domain>/<author>/<project>.git' template" >&2
-            exit 1
-        fi
+        exit 1
     fi
+
+    # get project name and author name from the given Git URL
+    git_url_project="$(echo "$git_url" | sed -E -e 's/.git$//; s|.*/||')"
+    git_url_author="$(echo "$git_url" | sed -E -e 's|/[^/]*$||; s|.*/||')"
 fi
 
 #-------------------------------------------------------------------------------
