Update gim

diff --git a/build/gim b/build/gim
--- a/build/gim
+++ b/build/gim
@@ -12,7 +12,7 @@
 #-------------------------------------------------------------------------------
 
 # list of required software
-SW_REQUIRED='command echo [ id git make cd'
+SW_REQUIRED='command echo [ git make cd mkdir sed'
 
 # check if some software is missing
 for i in $SW_REQUIRED; do
@@ -35,7 +35,12 @@ done
 # the current version of the program
 VERSION=1.0.0
 
-HELP_MESSAGE="Usage: $0 ACTION GIT_URL [OPTION]...
+HELP_MESSAGE="Usage: $0 [OPTION]... ACTION GIT_URL
+
+ACTION:
+  install    install the program originating from a given Git URL
+  uninstall  uninstall the program originating from a given Git URL
+  update     update the program originating from a given Git URL
 
 OPTION:
   -help     show this help and exit
@@ -49,33 +54,116 @@ Copy"'right 2018 Dominik Salvet
 SPDX License Identifier: MIT
 https://gitlab.com/dominiksalvet/gim'
 
+# cache directory used to store download Git repositories
+CACHE_DIR=~/.cache/gim
+
 #-------------------------------------------------------------------------------
 # PROCESSING PARAMETERS
 #-------------------------------------------------------------------------------
 
 # processing each parameter separately
 for i in "$@"; do
-    case "$i" in
-        -help)
-            echo "$HELP_MESSAGE"
-            exit 0
-            ;;
-        -about)
-            echo "$ABOUT_MESSAGE"
-            exit 0
-            ;;
-        -version)
-            echo "$VERSION"
-            exit 0
-            ;;
-        *)
-            echo "$0: The option '$i' was not recognized.
+    if [ ! -z "$action" ]; then
+        # the action has been selected in the previous variable, get Git URL
+        git_url="$i"
+        break
+    else
+        case "$i" in
+            install)
+                action=install
+                ;;
+            uninstall)
+                action=uninstall
+                ;;
+            update)
+                action=update
+                ;;
+            -help)
+                echo "$HELP_MESSAGE"
+                exit 0
+                ;;
+            -about)
+                echo "$ABOUT_MESSAGE"
+                exit 0
+                ;;
+            -version)
+                echo "$VERSION"
+                exit 0
+                ;;
+            *)
+                echo "$0: The option '$i' was not recognized.
 Try '$0 -help' for more information." >&2
-            exit 1
-            ;;
-    esac
+                exit 1
+                ;;
+        esac
+    fi
 done
+
+# check arguments if valid
+if [ -z "$action" ]; then
+    echo "$0: No argument with action provided.
+Try '$0 -help' for more information." >&2
+    exit 1
+else
+    if [ -z "$git_url" ]; then
+        echo "$0: No argument with URL provided.
+Try '$0 -help' for more information." >&2
+        exit 1
+    else
+        case "$git_url" in
+            *.git)
+                # parse project and author name from a given Git URL
+                git_url_project="$(echo "$git_url" | sed -E -e 's/.git$//; s|.*/||')"
+                git_url_author="$(echo "$git_url" | sed -E -e 's|/[^/]*$||; s|.*/||')"
+                ;;
+        esac
+
+        if [ -z "$git_url_project" ] || [ -z "$git_url_author" ]; then
+            echo "$0: Provided Git URL is invalid.
+POSSIBLE SOLUTIONS:
+  * use the 'https://<provider>.<domain>/<author>/<project>.git' template" >&2
+        fi
+    fi
+fi
 
 #-------------------------------------------------------------------------------
 # EXECUTE SELECTED ACTION
 #-------------------------------------------------------------------------------
+
+# create a cache directory for the program
+mkdir -p "$CACHE_DIR/$git_url_author/$git_url_project/"
+cd "$CACHE_DIR/$git_url_author/$git_url_project/" || exit 1
+
+# check if already existing a downloaded repository
+if [ -d ".git" ]; then
+    git checkout master
+    git pull
+    git getch --tags
+else
+    git clone "$git_url" .
+fi
+
+case "$action" in
+    install)
+        # use the latest repository tag
+        git checkout "$(git describe --abbrev=0)"
+        # install the program
+        make install
+        ;;
+    uninstall)
+        # use the program version as a tag
+        git checkout "$(gim -version)"
+        # uninstall the program
+        make uninstall
+        ;;
+    update)
+        # use the program version as a tag
+        git checkout "$(gim -version)"
+        # uninstall the program
+        make uninstall
+        # use the latest repository tag
+        git checkout "$(git describe --abbrev=0)"
+        # install the program again
+        make install
+        ;;
+esac
