Update gim root check message

diff --git a/build/gim b/build/gim
--- a/build/gim
+++ b/build/gim
@@ -18,7 +18,7 @@ SW_REQUIRED='command echo [ git make cd mkdir sed grep rm ls umask logname sudo 
 for i in $SW_REQUIRED; do
     # software is missing if at least one piece of software is missing
     if ! command -v "$i" > /dev/null; then
-        echo "$0: Required software '$i' is missing, action canceled." >&2
+        echo "$0: Required software '$i' is missing." >&2
         # the program dependencies may be missing
         if [ "$i" = hda-verb ]; then
             echo 'POSSIBLE SOLUTIONS:
