Remaster uninstallation script

diff --git a/make/uninstall b/make/uninstall
--- a/make/uninstall
+++ b/make/uninstall
@@ -11,6 +11,12 @@
 
 
 #-------------------------------------------------------------------------------
+# GLOBAL DIRECTIVES
+#-------------------------------------------------------------------------------
+# shellcheck disable=1090
+#-------------------------------------------------------------------------------
+
+#-------------------------------------------------------------------------------
 # SOFTWARE DEPENDENCIES
 #-------------------------------------------------------------------------------
 
@@ -31,12 +37,16 @@ done
 
 # check if the source directory argument is correct
 if [ ! "$1" ] || [ ! -d "$1"/ ]; then
-    echo "$0: first argument must be an existing directory's path" >&2
+    echo "$0: first argument must be the path of an existing directory" >&2
     exit 1
 fi
 
+# verify that required environment variables were provided
+: "${GLOBAL_CFG_DIR:?}"
+: "${LOCAL_CFG_DIR:?}"
+
 #-------------------------------------------------------------------------------
-# INITIALIZATION
+# LOADING VARIABLES
 #-------------------------------------------------------------------------------
 
 # check installation type
@@ -48,56 +58,76 @@ if [ ! "$INSTALL_TYPE" ]; then
     fi
 fi
 
-# load environment variables
+# load configuration from RC files
 if [ "$INSTALL_TYPE" = global ]; then
-    if [ -r /etc/gimrc ]; then
-        . /etc/gimrc
-    else
-        . "$1"/rc/global
+    . "$1"/rc/global && # use delivered global RC file
+    if [ -r "$GLOBAL_CFG_DIR"/gimrc ]; then
+        . "$GLOBAL_CFG_DIR"/gimrc # custom user-defined RC file
     fi
 else
-    if [ -r "$HOME"/.gimrc ]; then
-        . "$HOME"/.gimrc
-    else
-        . "$1"/rc/local
+    . "$1"/rc/local && # use delivered local RC file
+    if [ -r "$LOCAL_CFG_DIR"/gimrc ]; then
+        . "$LOCAL_CFG_DIR"/gimrc # custom user-defined RC file
     fi
 fi || exit
 
-# verify that required variables were loaded
-: "${GIM_DB_DIR:?}"
-: "${GIM_BIN_DIR:?}"
+#-------------------------------------------------------------------------------
+# GIM_DB_DIR checks
+#-------------------------------------------------------------------------------
 
-# verify that this script can access to the directories
-if [ ! -w "$GIM_DB_DIR" ]; then
-    echo "$0: can't write to $GIM_DB_DIR" >&2
+# the file representing a database of locally installed projects
+readonly GIM_STATUS_PATH="${GIM_DB_DIR:?}"/status
+
+if [ -e "$GIM_STATUS_PATH" ] && [ ! -w "$GIM_STATUS_PATH" ]; then
+    echo "$0: can't write to $GIM_STATUS_PATH" >&2
     exit 1
 fi
-if [ ! -w "$GIM_BIN_DIR" ]; then
+
+#-------------------------------------------------------------------------------
+# GIM_BIN_DIR checks
+#-------------------------------------------------------------------------------
+
+# verify that the gim binary path variable is set
+: "${GIM_BIN_DIR:?}"
+
+if [ -e "$GIM_BIN_DIR"/ ] && [ ! -w "$GIM_BIN_DIR"/ ]; then
     echo "$0: can't write to $GIM_BIN_DIR" >&2
     exit 1
 fi
-
-# create additional constants
-readonly GIM_STATUS_PATH="$GIM_DB_DIR"/status
 
 #-------------------------------------------------------------------------------
 # UNINSTALLATION
 #-------------------------------------------------------------------------------
 
 # remove program files
-rm -f /etc/bash_completion.d/gim-completion &&
 rm -f "$GIM_BIN_DIR"/gim &&
 
-# if INSTALLER is gim, it is possible that gim is calling this script
-# if INSTALLER is not gim, erase record of installation from gim's database manually
+# remove default gimrc files
+if [ "$INSTALL_TYPE" = global ]; then
+    rm -f "$GLOBAL_CFG_DIR"/gimrc-local &&
+    rm -f "$GLOBAL_CFG_DIR"/gimrc-global
+else
+    rm -f "$LOCAL_CFG_DIR"/gimrc-local
+fi &&
+
+# remove TAB completion
+if [ "$INSTALL_TYPE" = global ]; then
+    rm -f /etc/bash_completion.d/gim-completion
+else
+    rm -f "$HOME"/.bash_completion.d/gim-completion
+fi &&
+
+# if INSTALLER is not gim, it is required to modify gim status file manually
 if [ "$INSTALLER" != gim ]; then
-    if [ -f "$GIM_STATUS_PATH" ]; then
+    if [ -e "$GIM_STATUS_PATH" ]; then
         # get short hash of the current git commit
         readonly COMMIT_SHORT_HASH="$(git rev-parse --short HEAD)" &&
         # use tag name pointing to the commit as gim version if any
         commit_gim_version="$(git tag -l --points-at "$COMMIT_SHORT_HASH")" &&
         # if no tags found, use short commit hash as gim version
-        commit_gim_version="${commit_gim_version:-"$commit_short_hash"}" &&
+        commit_gim_version="${commit_gim_version:-"$COMMIT_SHORT_HASH"}" &&
         sed -i -E -e '\|'"gitlab.com/dominiksalvet/gim $commit_gim_version"'|d' "$GIM_STATUS_PATH"
+    else
+        echo > "$GIM_STATUS_PATH"
     fi
 fi || exit
