Fix error reporting during cloning/fetching

diff --git a/src/gim b/src/gim
--- a/src/gim
+++ b/src/gim
@@ -40,7 +40,7 @@ ACTION:
   install    install a Git project
   update     update a Git project
   uninstall  uninstall a Git project
-  status     show a Git project status
+  status     show status of a Git project
 
 COMMAND:
   -autoclean  remove old cache and exit
@@ -86,12 +86,12 @@ autoclean() {
         fi
     done
     # remove maintainer directories if they are empty
-    for _maintainer_dir in "${CACHE_REPO_DIR:?}/"*/*; do
-        rmdir --ignore-fail-on-non-empty "$_maintainer_dir/"
+    for _maintainer_dir in "$CACHE_REPO_DIR"/*/*; do
+        rmdir --ignore-fail-on-non-empty "$_maintainer_dir"/
     done
     # remove hostname directories if they are empty
-    for _hostname_dir in "${CACHE_REPO_DIR:?}/"*; do
-        rmdir --ignore-fail-on-non-empty "$_hostname_dir/"
+    for _hostname_dir in "$CACHE_REPO_DIR"/*; do
+        rmdir --ignore-fail-on-non-empty "$_hostname_dir"/
     done
 }
 
@@ -145,13 +145,16 @@ call_make() {
 #-------------------------------------------------------------------------------
 
 action=
-repo_url=
+repo_long_url=
+repo_short_url=
 make_args=
 # process each argument individually
 for arg in "$@"; do
     if [ ! -z "$action" ]; then # if the action has been selected
-        if [ -z "$repo_url" ]; then # if the project repository URL is not set
-            repo_url="$arg" # next up are only make arguments
+        if [ -z "$repo_long_url" ]; then # if the project repository URL is not set
+            # set up both URL variables for later processing
+            repo_long_url="$arg"
+            repo_short_url="$arg"
         # accept only make arguments
         elif [ -z "$make_args" ]; then
             make_args="$arg"
@@ -181,7 +184,7 @@ for arg in "$@"; do
             -clean)
                 # check if running as root
                 root_check || exit
-                rm -r -f "${CACHE_REPO_DIR:?}/"*
+                rm -r -f "${CACHE_REPO_DIR:?}"/*
                 exit 0
                 ;;
             -help)
@@ -205,37 +208,31 @@ $HINT_MESSAGE" >&2
     fi
 done
 
-# check arguments if valid and parse required information
-if [ -z "$action" ]; then # check if argument with an action provided
-    echo "$0: No argument with action provided.
-$HINT_MESSAGE" >&2
-    exit 1
-fi
-
-# check if argument with repository URL provided
-if [ -z "$repo_url" ]; then
-    echo "$0: No argument with repository URL provided.
+# check if arguments provided
+if [ -z "$action" ] || [ -z "$repo_long_url" ]; then
+    echo "$0: Required arguments not provided.
 $HINT_MESSAGE" >&2
     exit 1
 fi
 
 # check the format of given repository URL
-if ! echo "$repo_url" | grep -q -E -e '^(|https://)[^/]+(/[^\.][^/]*){2}(|\.git)$'; then
-    echo "$0: Supplied repository URL is not valid.
-$HINT_MESSAGE" >&2
+if ! echo "$repo_long_url" | grep -q -E -e '^(|https://)[^/]+(/[^\.][^/]*){2}(|\.git)$'; then
+    echo "$0: Supplied repository URL is not valid." >&2
     exit 1
 fi
 
 # if the repository URL doesn't start with 'https://'
-if ! echo "$repo_url" | grep -q -E -e '^https://'; then
-    # add 'https://'
-    repo_url="https://$repo_url"
+if ! echo "$repo_long_url" | grep -q -E -e '^https://'; then
+    repo_long_url=https://"$repo_long_url"
+else
+    repo_short_url="$(echo "$repo_short_url" | sed -E -e 's|^https://||')"
 fi
 
 # if the repository URL doesn't end with '.git'
-if ! echo "$repo_url" | grep -q -E -e '\.git$'; then
-    # append '.git'
-    repo_url="${repo_url}.git"
+if ! echo "$repo_long_url" | grep -q -E -e '\.git$'; then
+    repo_long_url="$repo_long_url".git
+else
+    repo_short_url="$(echo "$repo_short_url" | sed -E -e 's/\.git$//')"
 fi
 
 #-------------------------------------------------------------------------------
@@ -246,24 +243,18 @@ fi
 root_check || exit
 
 # extract required information from the given repository URL
-repository_hostname="$(echo "$repo_url" | sed -E -e 's|^https://||; s|/.*$||')"
-repository_maintainer="$(echo "$repo_url" | sed -E -e 's|/[^/]*$||; s|.*/||')"
-repository_name="$(echo "$repo_url" | sed -E -e 's/.git$//; s|.*/||')"
-repository_dir="$CACHE_REPO_DIR/$repository_hostname/$repository_maintainer/$repository_name"
+repo_hostname="$(echo "$repo_short_url" | sed -E -e 's|/.*$||')"
+repo_maintainer="$(echo "$repo_short_url" | sed -E -e 's|/[^/]*$||; s|.*/||')"
+repo_name="$(echo "$repo_short_url" | sed -E -e 's|.*/||')"
+repo_dir="$CACHE_REPO_DIR/$repo_hostname/$repo_maintainer/$repo_name"
 
 # create a cache directory for the project
-mkdir -p "$repository_dir/" &&
-cd "$repository_dir/" || {
-    echo "$0: Can't access gim's cache directory.
-POSSIBLE SOLUTIONS:
-  * Free up some storage space.
-  * Contact a gim developer." >&2
-    exit 1
-}
+mkdir -p "$repo_dir/" &&
+cd "$repo_dir/" &&
 
 if [ -z "$(ls -A)" ]; then # if the cache directory for the target project is empty
     # clone the Git repository master branch to the this directory
-    git clone -q --progress --branch master --single-branch "$repo_url" .
+    git clone -q --progress --branch master --single-branch "$repo_long_url" . &&
     # disable push remote URL
     git remote set-url --push origin ''
 else
@@ -273,44 +264,44 @@ else
     git reset -q --hard &&
 
     # apply given fetch remote URL
-    git remote set-url origin "$repo_url"
+    git remote set-url origin "$repo_long_url" &&
     # fetch changes to master branch together with all repository tags
     git fetch -q --progress --tags origin master &&
     # merge all fetched remote master changes with local master branch
     git merge -q FETCH_HEAD
 fi || {
-    echo "$0: Can't obtain $repository_name repository in the most recent state.
+    echo "$0: Can't obtain $repo_name repository in the most recent state.
 POSSIBLE SOLUTIONS:
-  * Make sure that $repository_name repository exists on the given URL.
   * Connect your device to the Internet.
-  * Remove the cache using the 'sudo $0 -clean' command.
+  * Make sure that $repo_name repository exists on the given URL.
+  * Remove all cache using the 'sudo $0 -clean' command.
   * Free up some storage space." >&2
     exit 1
 }
 
+#-------------------------------------------------------------------------------
+# CHECK VERSIONS
+#-------------------------------------------------------------------------------
+
 # get version of the most recent annotated tag of the obtained Git project
-repository_project_version="$(git describe --abbrev=0)" || {
-    echo "$0: Repository $repository_name has no annotated tag.
+repo_project_version="$(git describe --abbrev=0)" || {
+    echo "$0: Repository $repo_name has no annotated tag.
 POSSIBLE SOLUTIONS:
-  * Contact a $repository_name repository developer about gim compliance." >&2
+  * Contact a $repo_name repository developer about gim compliance." >&2
     exit 1
 }
 
-#-------------------------------------------------------------------------------
-# CHECK VERSION
-#-------------------------------------------------------------------------------
-
 # get information about the local project (if installed)
-local_project_name="$(get_local_project_name "$repository_dir/")"
+local_project_name="$(get_local_project_name "$repo_dir/")"
 local_project_version="$(get_local_project_version "$local_project_name")"
 
-if [ -r "$repository_dir/gim/unsupported" ] && [ ! -z "$local_project_version" ]; then
-    if head -n 1 "$repository_dir/gim/unsupported" | grep -q -E -e "$local_project_version"; then
+if [ -r "$repo_dir/gim/unsupported" ] && [ ! -z "$local_project_version" ]; then
+    if head -n 1 "$repo_dir/gim/unsupported" | grep -q -E -e "$local_project_version"; then
         echo "$0: [$local_project_name $local_project_version] is not gim compliant.
 POSSIBLE SOLUTION:
   * Use delivered makefile to perform '$action' action.
   * Visit a project website for more information.
-  * Contact a $repository_name repository developer." >&2
+  * Contact a $repo_name repository developer." >&2
         exit 1
     fi
 fi
@@ -322,7 +313,7 @@ fi
 case "$action" in
     install)
         if [ ! -z "$local_project_name" ]; then # check if the project already installed
-            if [ "$local_project_version" = "$repository_project_version" ]; then # if the versions are the same
+            if [ "$local_project_version" = "$repo_project_version" ]; then # if the versions are the same
                 echo "[$local_project_name $local_project_version] is already installed and updated."
                 exit 0
             elif [ -z "$local_project_version" ]; then # if not and version flags not supported
@@ -331,19 +322,19 @@ POSSIBLE SOLUTIONS:
   * Contact a $local_project_name developer about gim compliance." >&2
                 exit 1
             else
-                echo "$0: [$local_project_name $local_project_version] is already installed but not updated ($repository_project_version).
+                echo "$0: [$local_project_name $local_project_version] is already installed but not updated ($repo_project_version).
 POSSIBLE SOLUTIONS:
   * Use the 'update' action instead of the used 'install' action." >&2
                 exit 1
             fi
         fi
 
-        git checkout -q "$repository_project_version" && # use the latest repository tag
+        git checkout -q "$repo_project_version" && # use the latest repository tag
         call_make install "$make_args" # install the program
         ;;
     update)
         if [ ! -z "$local_project_name" ]; then # check if the project installed
-            if [ "$local_project_version" = "$repository_project_version" ]; then # if the versions are the same
+            if [ "$local_project_version" = "$repo_project_version" ]; then # if the versions are the same
                 echo "[$local_project_name $local_project_version] is already installed and updated."
                 exit 0
             elif [ -z "$local_project_version" ]; then # if not and version flags not supported
@@ -353,7 +344,7 @@ POSSIBLE SOLUTIONS:
                 exit 1
             fi
         else # the project is not installed
-            echo "$0: There is nothing installed from $repository_name repository.
+            echo "$0: There is nothing installed from $repo_name repository.
 POSSIBLE SOLUTIONS:
   * Use the 'install' action instead of the used 'update' action." >&2
             exit 1
@@ -362,12 +353,12 @@ POSSIBLE SOLUTIONS:
         git checkout -q "$local_project_version" && # use the program version as a tag
         call_make uninstall "$make_args" && # uninstall the program
 
-        git checkout -q "$repository_project_version" && # use the latest repository tag
+        git checkout -q "$repo_project_version" && # use the latest repository tag
         call_make install "$make_args" # install the program again
         ;;
     uninstall)
         if [ -z "$local_project_name" ]; then # if the project is not installed
-            echo "There is nothing installed from $repository_name repository."
+            echo "There is nothing installed from $repo_name repository."
             exit 0 # uninstallation exits with a success eventually
         elif [ -z "$local_project_version" ]; then
             echo "$0: [$local_project_name] is installed but no version information was provided.
@@ -381,14 +372,14 @@ POSSIBLE SOLUTIONS:
         ;;
     status)
         if [ -z "$local_project_name" ]; then # if the project is not installed
-            echo "There is nothing installed from $repository_name repository."
+            echo "There is nothing installed from $repo_name repository."
         else # project installed
-            if [ "$local_project_version" = "$repository_project_version" ]; then # if the versions are the same
+            if [ "$local_project_version" = "$repo_project_version" ]; then # if the versions are the same
                 echo "[$local_project_name $local_project_version] is installed and updated."
             elif [ -z "$local_project_version" ]; then # if not and version flags not supported
                 echo "[$local_project_name] is installed but no version information was provided."
             else
-                echo "[$local_project_name $local_project_version] is installed but not updated ($repository_project_version)."
+                echo "[$local_project_name $local_project_version] is installed but not updated ($repo_project_version)."
             fi
         fi
 
@@ -401,7 +392,7 @@ POSSIBLE SOLUTIONS:
     if [ ! -z "$local_project_name" ]; then
         echo "  * Contact a $local_project_name developer." >&2
     else
-        echo "  * Contact a $repository_name repository developer." >&2
+        echo "  * Contact a $repo_name repository developer." >&2
     fi
     exit 1
 }
@@ -414,15 +405,15 @@ POSSIBLE SOLUTIONS:
 git checkout -q master
 
 # refresh information about the local project
-new_local_project_name="$(get_local_project_name "$repository_dir/")"
+new_local_project_name="$(get_local_project_name "$repo_dir/")"
 new_local_project_version="$(get_local_project_version "$new_local_project_name")"
 
 case "$action" in
     install)
         if [ -z "$new_local_project_name" ]; then # if the project is not installed (as it should be now)
-            echo "$0: A project from $repository_name repository should have been installed, but it is not.
+            echo "$0: A project from $repo_name repository should have been installed, but it is not.
 POSSIBLE SOLUTIONS:
-  * Contact a $repository_name repository developer about gim compliance.
+  * Contact a $repo_name repository developer about gim compliance.
   * Install the project again." >&2
             exit 1
         else
@@ -431,9 +422,9 @@ POSSIBLE SOLUTIONS:
         ;;
     update)
         if [ -z "$new_local_project_name" ]; then # if the project is not installed (as it should be now)
-            echo "$0: [$local_project_name $local_project_version] has been uninstalled but it couldn't have been updated ($repository_project_version).
+            echo "$0: [$local_project_name $local_project_version] has been uninstalled but it couldn't have been updated ($repo_project_version).
 POSSIBLE SOLUTIONS:
-  * Contact a $repository_name repository developer about gim compliance.
+  * Contact a $repo_name repository developer about gim compliance.
   * Use the 'install' action instead of the used 'update' action." >&2
             exit 1
         else
@@ -444,7 +435,7 @@ POSSIBLE SOLUTIONS:
         if [ ! -z "$new_local_project_name" ]; then # if the project is installed (as it shouldn't be now)
             echo "$0: [$new_local_project_name $new_local_project_version] should have been uninstalled, but it is not.
 POSSIBLE SOLUTIONS:
-  * Contact a $repository_name repository developer about gim compliance.
+  * Contact a $repo_name repository developer about gim compliance.
   * Uninstall the project again." >&2
             exit 1
         else
