Update gim-completion

diff --git a/src/gim-completion b/src/gim-completion
--- a/src/gim-completion
+++ b/src/gim-completion
@@ -1,7 +1,16 @@
 #-------------------------------------------------------------------------------
-# Copyright 2018 Dominik Salvet
+# Copyright 2018-2019 Dominik Salvet
 # SPDX-License-Identifier: MIT
 # https://gitlab.com/dominiksalvet/gim
+#-------------------------------------------------------------------------------
+
+#-------------------------------------------------------------------------------
+# DESCRIPTION
+#-------------------------------------------------------------------------------
+# This file is expected to be sourced. It implements a TAB completion for Bash
+# terminal environments.
+# 
+# The text after '#' character represents a comment.
 #-------------------------------------------------------------------------------
 
 
@@ -9,16 +18,13 @@
 # SOFTWARE DEPENDENCIES
 #-------------------------------------------------------------------------------
 
-# list of required software
-SW_REQUIRED='command [ compgen complete'
+# a list of required software
+readonly SW_REQUIRED='command echo [ compgen complete'
 
-# check if some software is missing
-for i in $SW_REQUIRED; do
-    # software is missing if at least one piece of software is missing
-    if ! command -v "$i" > /dev/null; then
-        echo "$0: Required software $i is missing.
-POSSIBLE SOLUTIONS:
-  * Install $i using an installed package manager." >&2
+# check if any piece of software is missing
+for sw in $SW_REQUIRED; do
+    if ! command -v -- "$sw" > /dev/null; then
+        echo "$0: missing $sw software" >&2
         exit 1
     fi
 done
